capsul laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Blog;
use Jenssegers\Agent\Agent;

Route::get('/', function () {
    $agent = new Agent();
    if ($agent->isPhone() and $agent->isSafari() and Auth::check())
        return redirect()->route('panel');
    return view('home');
})->name('home');

Route::get('blog', function () {
    $blogs = Blog::all();
    return view('blog.index', ['blogs' => $blogs]);
})->name('blog');

Route::get('ios', function () {
    return redirect()->route('login');
})->name('iosGet');
Route::post('ios', function () {
    $agent = new Agent();
    if ($agent->isSafari())
        return view('ios')->with(['safari'=>true]);
    return view('ios');
})->name('iosPost');

//Route::get('/', 'Auth\LoginController@showLoginForm')->name('home');

Route::get('/terms/client', function (Request $request) {
    return view('terms', ['for' => 'client']);
})->name('termsClient');
Route::get('/terms/dr', function (Request $request) {
    return view('terms', ['for' => 'dr']);
})->name('termsDr');

Auth::routes();

// Authentication routes with throttle
// Later we have to add recaptcha to this routes
// every 1 min 3000 requests
Route::middleware('throttle:2,1')->group(function () {
    Route::post('register', 'Auth\RegisterController@register');
    Route::post('login', 'Auth\LoginController@login');
});
Route::middleware('throttle:2,2')->group(function () {
    Route::post('forgotPass', 'Auth\ForgotPasswordController@recoverPassSms')->name('forgotPassSMS');
});

// Resources without auth
Route::get('register/client', 'Auth\RegisterController@showRegistrationFormClient')->name('registerClient');
Route::get('register/doctor', 'Auth\RegisterController@showRegistrationFormDoctor')->name('registerDoctor');
Route::get('/payir', 'PaymentController@pay')->name('pay');
Route::get('/payir/callback', 'PaymentController@verify');


// Routes need auth
Route::middleware(['auth', 'role'])->group(function () {
    Route::get('panel', 'PanelController@index')->name('panel');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::resource('reqs', 'UserRequestController');
    Route::get('profile', 'Auth\LoginController@current_user')->name('profile');
    Route::match(['put', 'patch'], 'user/update', 'Auth\RegisterController@update')->name('updateProfile');
    Route::resource('sicks', 'UserSickController');
    Route::resource('complaints', 'ComplaintController');
    Route::resource('chats', 'ChatController');
    Route::get('wallet/increase', 'WalletController@increaseIndex')->name('wallet.index');
    Route::get('wallet/income', 'WalletController@income')->name('wallet.income');
    Route::post('wallet/increase', 'WalletController@increase')->name('wallet.increase');

    //dr routes should set middleware later
    Route::post('reqs/new/{req}', 'UserRequestController@acceptRequestDr')->name('acceptReq');
    Route::post('reqs/close/{req}', 'UserRequestController@closeRequestDr')->name('closeReq');
    Route::post('reqs/reject/{req}', 'UserRequestController@rejectRequestDr')->name('rejectReq');

    Route::group(['prefix' => env('ADMIN_PREFIX/') . 'admin'], function () {
        Voyager::routes();
        Route::get('reqs/cost/back', 'UserRequestController@costBack')->name('costBack');
        Route::get('doctor/accept', 'DoctorController@accept')->name('drAccept');
    });

});

capsul laravel/app/Client.php
<?php

namespace App;


class Client extends MotherModel
{
    protected $primaryKey = 'user_id';

    public function User()
    {
        return $this->belongsTo(User::class);
    }

    public function Requests()
    {
        return $this->hasMany(UserRequest::class);
    }

    public function InitHistory()
    {
        return $this->hasOne(InitHistory::class, 'user_id', 'user_id');
    }

    public function getNameAttribute($value)
    {
        if (isAdmin())
            return $value . "(" . $this->user_id . ")";
    }
}

capsul laravel/app/Complaint.php
<?php

namespace App;


class Complaint extends MotherModel
{
    protected $hidden = ['user_id', 'created_at', 'updated_at', 'deleted_at'];

    public function Doctor()
    {
        return $this->belongsTo(Doctor::class, 'dr_id', 'user_id')->with('User:id,fname,lname,sex,pic');
    }
}

capsul laravel/app/Http/Controllers/ComplaintController.php
<?php

namespace App\Http\Controllers;

use App\Complaint;
use App\Http\Resources\PublicJsonResource;
use App\Support;
use App\UserRequest;
use Illuminate\Http\Request;

class ComplaintController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Complaint[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    public function index(Request $request)
    {
        if (isClient())
            $complaints = Complaint::with('Doctor:user_id,dr_code')
                ->where('user_id', userId())->get();
        if (isDoctor())
            $complaints = Support::with('Doctor:user_id,dr_code')
                ->where('user_id', userId())->get();
        if ($request->expectsJson())
            return $complaints;
        if (isClient())
            return view('client.complaints.index', ['complaints' => $complaints]);
        if (isDoctor())
            return view('doctor.complaints.index', ['complaints' => $complaints]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if (isClient()) {
            $doctors = $this->doctors($request);
            if ($doctors->isEmpty()) {
                flashMsg('شما هیچ درخواستی با متخصصان ما نداشته‌اید بنابراین امکان ثبت پیشنهاد برای شما وجود ندارد.', 0);
                return redirect()->back();
            }
            return view('client.complaints.create', ['reqDoctors' => $doctors]);
        }
        if (isDoctor())
            return view('doctor.complaints.create', ['reqDoctors' => $this->doctors($request)]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (isDoctor()) {
            $request->validate([
                'title' => 'required|string|max:100',
                'desc' => 'required|string|max:500',
            ]);
            $request['user_id'] = userId();
            Support::create($request->only('title', 'desc', 'user_id'));
        }
        if (isClient()) {
            $request->validate([
                'dr_id' => 'required|exists:doctors,user_id',
                'title' => 'required|string|max:100',
                'desc' => 'required|string|max:500',
            ]);
            if (array_key_exists($request->dr_id, $this->doctors($request, true)))
                return errorResp('درخواستی از شما که توسط دکتر مورد نظر قبول شده باشد یافت نشد.');
            $request['user_id'] = userId();
            Complaint::create($request->only('dr_id', 'title', 'desc', 'user_id'));
        }
        $msg = 'با موفقیت ثبت شد.';
        if ($request->expectsJson())
            return apiResp($msg);
        flashMsg($msg);
        return redirect(route('complaints.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Complaint $complaint
     * @return Complaint|\Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model|object
     */
    public function show(Complaint $complaint)
    {
//        return $complaint->with('Doctor:user_id,dr_code')
//            ->where('user_id', userId())->first();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Complaint $complaint
     * @return \Illuminate\Http\Response
     */
    public function edit(Complaint $complaint)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Complaint $complaint
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Complaint $complaint)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param \App\Complaint $complaint
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Request $request, Complaint $complaint)
    {
//        $complaint->delete();
//        $msg = 'شکایت حذف شد.';
//        if ($request->expectsJson())
//            return apiResp($msg);
//        flashMsg('شکایت حذف شد.', 0);
//        return redirect()->back();
    }

    public function doctors(Request $request, $array_response = false)
    {
        $doctors = UserRequest::where('user_id', userId())
            ->whereIn('status', ['accepted', 'finished']);
        if ($array_response)
            return $doctors->pluck('dr_id')->unique();
        else if ($request->expectsJson()) {
            $newDr = $doctors->select('dr_id')->with('Doctor:user_id')->get()->unique('user_id');
            $newDr->each(function ($dr) {
                $dr->setAppends([]);
            });
            return $newDr;
        }
        return $doctors->with('Doctor')->get()->unique('user_id');
    }
}

capsul laravel/resources/views/client/complaints/create.blade.php
@extends('layouts.client.clientPanel')

@section('content')
    <div class="row mt-3">
        <div class="col-12 mx-auto" style="max-width: 500px">
            <div class="card card-primary mt-3">
                <div class="card-header">
                    <h3 class="card-title">ثبت پیشنهاد</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('complaints.store')}}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="title" class="col-sm-10 control-label">عنوان پیشنهاد</label>

                            <div class="col-sm-10">
                                    <textarea name="title" rows=2
                                              class="form-control @error('title') is-invalid @enderror" id="title"
                                              placeholder="عنوان شکایت را وارد کنید">{{old('title')}}</textarea>
                                @error('title')
                                <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-10 control-label" for="inputExp">دکتر مربوطه</label>
                            <div class="col-sm-10">

                                <select class="form-control @error('dr_id') is-invalid @enderror"
                                        id="inputExp" name="dr_id" required>
                                    <option selected disabled>انتخاب کنید</option>
                                    @foreach($reqDoctors as $req)
                                        <option value="{{$req->dr_id}}"
                                                @if (old('dr_id') == $req->id) selected @endif>{{$req->Doctor->User->fname .' '. $req->Doctor->User->lname}}</option>
                                    @endforeach
                                </select>
                                @error('dr_id')
                                <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="desc" class="col-sm-10 control-label">توضیحات را وارد کنید</label>

                            <div class="col-sm-10">
                                    <textarea name="desc" rows=2
                                              class="form-control @error('desc') is-invalid @enderror" id="desc"
                                              placeholder="توضیحات مربوطه را بنویسید">{{old('desc')}}</textarea>
                                @error('desc')
                                <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">تایید</button>
                        <a href="{{route('complaints.index')}}" class="btn btn-primary pull-left">بازگشت</a></div>
                </form>
            </div>
        </div>
    </div>

@endsection

capsul laravel/resources/views/client/complaints/index.blade.php
@extends('layouts.client.clientPanel')

@section('content')
    <div class="card card-primary mt-3">
        <div class="card-header">
            <h3 class="card-title">پیشنهادات</h3>
        </div>
        <div class="card-body row">
            @if($complaints->isEmpty())
                <div class="w-100 text-center">
                    <h5 class="text-warning">پیشنهادی ثبت نشده است</h5>

                </div>
            @endif
            @foreach($complaints as $comp)
                <div class="card card-light col-lg-4">
                    <div class="card-header">
                        <span class="ill-name text-white">{{$comp->title}}</span>
                        @php
                            $dateTime = new \Hekmatinasser\Verta\Verta($comp->created_at);
                            $date = $dateTime->format('Y/n/j');
                        @endphp
                        <span class="pull-left text-white">{{$date}}</span><br>
                        @if($comp->status == 'accepted')
                            <span class="float-left badge badge-success">{{translateCompStatus($comp)}}</span>
                        @elseif($comp->status == 'waiting')
                            <span class="float-left badge badge-warning">{{translateCompStatus($comp)}}</span>
                        @elseif($comp->status == 'reserved')
                            <span class="float-left badge badge-info">{{translateCompStatus($comp)}}</span>
                        @elseif($comp->status == 'finished')
                            <span class="float-left badge badge-dark">{{translateCompStatus($comp)}}</span>
                        @else
                            <span class="float-left badge badge-danger">{{translateCompStatus($comp)}}</span>
                        @endif


                    </div>
                    <div class="card-body">
                        <h5>توضیحات: </h5>
                        <p>{{$comp->desc}}</p>
                        <div class="form-group">
                            <label for="inputForDiag">پاسخ:</label>
                            @if($comp->answer)
                                <textarea class="form-control mt-3" id="inputForDiag" rows="1"
                                          disabled>{{$comp->answer}}</textarea>
                            @else
                                <p class="text-warning" id="inputForAdvise">پاسخی دریافت نشده است</p>
                            @endif
                        </div>
                    </div>
{{--                    <div class="card-footer">--}}
{{--                        @if($comp->status == 'waiting')--}}
{{--                            <div class="w-100">--}}
{{--                                <button class="btn btn-danger pull-left" data-toggle="modal"--}}
{{--                                        data-target="#deleteModal{{$loop->index}}" >حذف</button>--}}
{{--                            </div>--}}
{{--                        @endif--}}
{{--                    </div>--}}
                </div>
                    @if($comp->user_id == userId() and $comp->status == 'waiting')
                        <div class="modal fade" id="deleteModal{{$loop->index}}" tabindex="-1" role="dialog" aria-labelledby="rateModal"
                             aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">حذف پیشنهاد</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form action="{{route('complaints.destroy',['id' => $comp->id])}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <div class="modal-body">
                                            <h4 class="text-danger">آیا مطمئن هستید که این پیشنهاد حذف شود؟</h4>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-success mx-2">بله</button>
                                            <button type="button" class="btn btn-primary justify-content-end" data-dismiss="modal">خیر
                                            </button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    @endif

                @endforeach

            <div class="card-footer text-center w-100">
                <a href="{{route('complaints.create')}}" class="btn btn-lg btn-primary">ثبت پیشنهاد جدید</a>
            </div>
        </div>
    </div>

@endsection