capsul laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Blog;
use Jenssegers\Agent\Agent;

Route::get('/', function () {
    $agent = new Agent();
    if ($agent->isPhone() and $agent->isSafari() and Auth::check())
        return redirect()->route('panel');
    return view('home');
})->name('home');

Route::get('blog', function () {
    $blogs = Blog::all();
    return view('blog.index', ['blogs' => $blogs]);
})->name('blog');

Route::get('ios', function () {
    return redirect()->route('login');
})->name('iosGet');
Route::post('ios', function () {
    $agent = new Agent();
    if ($agent->isSafari())
        return view('ios')->with(['safari'=>true]);
    return view('ios');
})->name('iosPost');

//Route::get('/', 'Auth\LoginController@showLoginForm')->name('home');

Route::get('/terms/client', function (Request $request) {
    return view('terms', ['for' => 'client']);
})->name('termsClient');
Route::get('/terms/dr', function (Request $request) {
    return view('terms', ['for' => 'dr']);
})->name('termsDr');

Auth::routes();

// Authentication routes with throttle
// Later we have to add recaptcha to this routes
// every 1 min 3000 requests
Route::middleware('throttle:2,1')->group(function () {
    Route::post('register', 'Auth\RegisterController@register');
    Route::post('login', 'Auth\LoginController@login');
});
Route::middleware('throttle:2,2')->group(function () {
    Route::post('forgotPass', 'Auth\ForgotPasswordController@recoverPassSms')->name('forgotPassSMS');
});

// Resources without auth
Route::get('register/client', 'Auth\RegisterController@showRegistrationFormClient')->name('registerClient');
Route::get('register/doctor', 'Auth\RegisterController@showRegistrationFormDoctor')->name('registerDoctor');
Route::get('/payir', 'PaymentController@pay')->name('pay');
Route::get('/payir/callback', 'PaymentController@verify');


// Routes need auth
Route::middleware(['auth', 'role'])->group(function () {
    Route::get('panel', 'PanelController@index')->name('panel');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::resource('reqs', 'UserRequestController');
    Route::get('profile', 'Auth\LoginController@current_user')->name('profile');
    Route::match(['put', 'patch'], 'user/update', 'Auth\RegisterController@update')->name('updateProfile');
    Route::resource('sicks', 'UserSickController');
    Route::resource('complaints', 'ComplaintController');
    Route::resource('chats', 'ChatController');
    Route::get('wallet/increase', 'WalletController@increaseIndex')->name('wallet.index');
    Route::get('wallet/income', 'WalletController@income')->name('wallet.income');
    Route::post('wallet/increase', 'WalletController@increase')->name('wallet.increase');

    //dr routes should set middleware later
    Route::post('reqs/new/{req}', 'UserRequestController@acceptRequestDr')->name('acceptReq');
    Route::post('reqs/close/{req}', 'UserRequestController@closeRequestDr')->name('closeReq');
    Route::post('reqs/reject/{req}', 'UserRequestController@rejectRequestDr')->name('rejectReq');

    Route::group(['prefix' => env('ADMIN_PREFIX/') . 'admin'], function () {
        Voyager::routes();
        Route::get('reqs/cost/back', 'UserRequestController@costBack')->name('costBack');
        Route::get('doctor/accept', 'DoctorController@accept')->name('drAccept');
    });

});

capsul laravel/app/Client.php
<?php

namespace App;


class Client extends MotherModel
{
    protected $primaryKey = 'user_id';

    public function User()
    {
        return $this->belongsTo(User::class);
    }

    public function Requests()
    {
        return $this->hasMany(UserRequest::class);
    }

    public function InitHistory()
    {
        return $this->hasOne(InitHistory::class, 'user_id', 'user_id');
    }

    public function getNameAttribute($value)
    {
        if (isAdmin())
            return $value . "(" . $this->user_id . ")";
    }
}

capsul laravel/app/Sick.php
<?php

namespace App;


class Sick extends MotherModel
{
    protected $hidden = ['user_id', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * @return array
     */

}

capsul laravel/app/Http/Controllers/SickController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\PublicJsonResource;
use App\Sick;
use Illuminate\Http\Request;

class SickController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Sick[]|\Illuminate\Database\Eloquent\Collection
     */
    public function index(Request $request)
    {
        if ($request->expectsJson()) {
            return Sick::all();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Sick $sick
     * @return \Illuminate\Http\Response
     */
    public function show(Sick $sick)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Sick $sick
     * @return \Illuminate\Http\Response
     */
    public function edit(Sick $sick)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Sick $sick
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sick $sick)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Sick $sick
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sick $sick)
    {
        //
    }
}

capsul laravel/resources/views/client/sicks/create.blade.php
@extends('layouts.client.clientPanel')

@section('content')
    <div class="row mt-3">
        <div class="col-12 mx-auto" style="max-width: 500px">
            <div class="card card-primary mt-3">
                <div class="card-header">
                    <h3 class="card-title">ثبت سابقه پزشکی</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('sicks.store')}}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="title" class="col-sm-10 control-label">نام بیماری</label>

                            <div class="col-sm-10">
                                    <textarea name="sick" rows=2
                                              class="form-control @error('sick') is-invalid @enderror" id="title"
                                              placeholder="نام بیماری را وارد کنید">{{old('sick')}}</textarea>
                                @error('sick')
                                <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc" class="col-sm-10 control-label">توضیحات</label>

                            <div class="col-sm-10">
                                    <textarea name="desc" rows=2
                                              class="form-control @error('desc') is-invalid @enderror" id="desc"
                                              placeholder="اقدامات درمانی، تشخیص انجام شده و دارو های درحال مصرف را وارد نمایید">{{old('desc')}}</textarea>
                                @error('desc')
                                <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">تایید</button>
                        <a href="{{route('sicks.index')}}" class="btn btn-primary pull-left">بازگشت</a></div>
                </form>
            </div>
        </div>
    </div>

@endsection

capsul laravel/resources/views/client/sicks/index.blade.php
@extends('layouts.client.clientPanel')

@section('content')
    <div class="card card-primary mt-3">
        <div class="card-header">
            <h3 class="card-title">سوابق پزشکی</h3>
        </div>
        <div class="card-body row">
            @if($sicks->isEmpty())
                <div class="w-100 text-center">
                    <h5 class="text-warning">سابقه‌ای ثبت نشده است</h5>
                </div>
            @endif
            @foreach($sicks as $sick)
                <div class="card card-light col-lg-4">
                    <div class="card-header">
                        <span class="ill-name text-white">{{$sick->sick}}</span>
                        @php
                            $dateTime = new \Hekmatinasser\Verta\Verta($sick->created_at);
                            $date = $dateTime->format('Y/n/j');
                        @endphp
                        <span class="pull-left text-white">{{$date}}</span><br>


                    </div>
                    <div class="card-body">
                        <h5>توضیحات: </h5>
                        <p>{{$sick->desc}}</p>
                    </div>
                    <div class="card-footer">
                        @if($sick->added_by == 'client')
                            <div class="w-100">
                                <button class="btn btn-danger pull-left" data-toggle="modal"
                                        data-target="#deleteModal{{$loop->index}}">حذف
                                </button>
                            </div>
                        @endif
                        @if($sick->added_by == 'dr')
                            <span class="badge badge-success pull-left m-2">توسط پزشک</span>
                        @endif
                    </div>
                </div>
                @if($sick->user_id == userId())
                    <div class="modal fade" id="deleteModal{{$loop->index}}" tabindex="-1" role="dialog"
                         aria-labelledby="rateModal"
                         aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">حذف سابقه پزشکی</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form action="{{route('sicks.destroy',['id' => $sick->id])}}" method="post">
                                    @csrf
                                    @method('delete')
                                    <div class="modal-body">
                                        <h4 class="text-danger">آیا مطمئن هستید که این سابقه حذف شود؟</h4>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-success mx-2">بله</button>
                                        <button type="button" class="btn btn-primary justify-content-end"
                                                data-dismiss="modal">خیر
                                        </button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                @endif

            @endforeach

        </div>
        <div class="card-footer">
            <div class="card-footer text-center w-100">
                <a href="{{route('sicks.create')}}" class="btn btn-lg btn-primary">ثبت بیماری جدید</a>
            </div>
        </div>
    </div>

@endsection