capsul laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Blog;
use Jenssegers\Agent\Agent;

Route::get('/', function () {
    $agent = new Agent();
    if ($agent->isPhone() and $agent->isSafari() and Auth::check())
        return redirect()->route('panel');
    return view('home');
})->name('home');

Route::get('blog', function () {
    $blogs = Blog::all();
    return view('blog.index', ['blogs' => $blogs]);
})->name('blog');

Route::get('ios', function () {
    return redirect()->route('login');
})->name('iosGet');
Route::post('ios', function () {
    $agent = new Agent();
    if ($agent->isSafari())
        return view('ios')->with(['safari'=>true]);
    return view('ios');
})->name('iosPost');

//Route::get('/', 'Auth\LoginController@showLoginForm')->name('home');

Route::get('/terms/client', function (Request $request) {
    return view('terms', ['for' => 'client']);
})->name('termsClient');
Route::get('/terms/dr', function (Request $request) {
    return view('terms', ['for' => 'dr']);
})->name('termsDr');

Auth::routes();

// Authentication routes with throttle
// Later we have to add recaptcha to this routes
// every 1 min 3000 requests
Route::middleware('throttle:2,1')->group(function () {
    Route::post('register', 'Auth\RegisterController@register');
    Route::post('login', 'Auth\LoginController@login');
});
Route::middleware('throttle:2,2')->group(function () {
    Route::post('forgotPass', 'Auth\ForgotPasswordController@recoverPassSms')->name('forgotPassSMS');
});

// Resources without auth
Route::get('register/client', 'Auth\RegisterController@showRegistrationFormClient')->name('registerClient');
Route::get('register/doctor', 'Auth\RegisterController@showRegistrationFormDoctor')->name('registerDoctor');
Route::get('/payir', 'PaymentController@pay')->name('pay');
Route::get('/payir/callback', 'PaymentController@verify');


// Routes need auth
Route::middleware(['auth', 'role'])->group(function () {
    Route::get('panel', 'PanelController@index')->name('panel');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::resource('reqs', 'UserRequestController');
    Route::get('profile', 'Auth\LoginController@current_user')->name('profile');
    Route::match(['put', 'patch'], 'user/update', 'Auth\RegisterController@update')->name('updateProfile');
    Route::resource('sicks', 'UserSickController');
    Route::resource('complaints', 'ComplaintController');
    Route::resource('chats', 'ChatController');
    Route::get('wallet/increase', 'WalletController@increaseIndex')->name('wallet.index');
    Route::get('wallet/income', 'WalletController@income')->name('wallet.income');
    Route::post('wallet/increase', 'WalletController@increase')->name('wallet.increase');

    //dr routes should set middleware later
    Route::post('reqs/new/{req}', 'UserRequestController@acceptRequestDr')->name('acceptReq');
    Route::post('reqs/close/{req}', 'UserRequestController@closeRequestDr')->name('closeReq');
    Route::post('reqs/reject/{req}', 'UserRequestController@rejectRequestDr')->name('rejectReq');

    Route::group(['prefix' => env('ADMIN_PREFIX/') . 'admin'], function () {
        Voyager::routes();
        Route::get('reqs/cost/back', 'UserRequestController@costBack')->name('costBack');
        Route::get('doctor/accept', 'DoctorController@accept')->name('drAccept');
    });

});

capsul laravel/app/Client.php
<?php

namespace App;


class Client extends MotherModel
{
    protected $primaryKey = 'user_id';

    public function User()
    {
        return $this->belongsTo(User::class);
    }

    public function Requests()
    {
        return $this->hasMany(UserRequest::class);
    }

    public function InitHistory()
    {
        return $this->hasOne(InitHistory::class, 'user_id', 'user_id');
    }

    public function getNameAttribute($value)
    {
        if (isAdmin())
            return $value . "(" . $this->user_id . ")";
    }
}

capsul laravel/resources/views/layouts/client/clientPanel.blade.php
@extends('layouts.main')
@section('title')
    <title>پنل کاربر</title>
@endsection
@section('body')
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav mr-auto">
                <!-- Messages Dropdown Menu -->
                <li class="nav-item">
                    <a href="{{route('chats.index')}}"
                       @if(unReadChats(request())) class="text-white-danger" @endif>
                        @if(unReadChats(request()))
                            <span class="badge badge-danger mx-2">{{unReadChats(request())}}</span>
                        @endif
                        <i class="fa fa-comments-o fa-2x"></i></a>
                </li>
            </ul>
        </nav>
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-light-success elevation-4 ">
            <!-- Brand Logo -->
            <a href="/" class="brand-link bg-gray-light">
                <img src="{{asset('home/images/capsul-logo.png')}}" alt="AdminLTE Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">پنل کاربر</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar" style="direction: ltr">
                <div style="direction: rtl">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="{{userPic() ?: asset('dist/img/avatar04.png')}}"
                                 class="img-circle elevation-2" alt="User Image"
                                 style="width: 3.5rem">
                        </div>
                        <div class="info">
                            <a class="d-block">{{Auth::user()->fname.' '.Auth::user()->lname}}</a>
                            <a class="d-block">کیف پول : {{userWallet()}} تومان</a>
                            {{--                            <a class="d-block">امتیاز مراجعه : 13</a>--}}
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                            data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                                 with font-awesome or any other icon font library -->
                            <li class="nav-item">
                                <a href="{{route('profile')}}" class="nav-link">
                                    <i class="nav-icon fa fa-user"></i>
                                    <p>
                                        پروفایل
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('reqs.index')}}" class="nav-link">
                                    <i class="nav-icon fa fa-file"></i>
                                    <p>
                                        درخواست‌ها
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('chats.index')}}" class="nav-link">
                                    <i class="nav-icon fa fa-file"></i>
                                    <p>
                                        پیام ها
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('sicks.index')}}" class="nav-link">
                                    <i class="nav-icon fa fa-folder-open"></i>
                                    <p>
                                        سوابق پزشکی
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('complaints.index')}}" class="nav-link">
                                    <i class="nav-icon fa fa-file-text"></i>
                                    <p>
                                        پیشنهادات
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('wallet.index')}}" class="nav-link">
                                    <i class="nav-icon fa fa-file-text"></i>
                                    <p>
                                        افزایش شارژ کیف پول
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('logout')}}" class="nav-link">
                                    <i class="nav-icon fa fa-sign-out"></i>
                                    <p>
                                        خروج
                                    </p>
                                </a>
                            </li>

                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @if(Session::has('message'))
                    <div class="text-center mx-auto my-2 five-second-fade w-75">
                        <div class="alert {{ Session::get('alert-class', 'alert-info')}} alert-dismissible"
                             role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"
                                    style="margin-left: 8px!important;">&times;
                            </button>
                            {{ Session::get('message') }}</div>
                    </div>
        @endif
        <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @yield('content')
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>

    </div>

@endsection