capsul laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Blog;
use Jenssegers\Agent\Agent;

Route::get('/', function () {
    $agent = new Agent();
    if ($agent->isPhone() and $agent->isSafari() and Auth::check())
        return redirect()->route('panel');
    return view('home');
})->name('home');

Route::get('blog', function () {
    $blogs = Blog::all();
    return view('blog.index', ['blogs' => $blogs]);
})->name('blog');

Route::get('ios', function () {
    return redirect()->route('login');
})->name('iosGet');
Route::post('ios', function () {
    $agent = new Agent();
    if ($agent->isSafari())
        return view('ios')->with(['safari'=>true]);
    return view('ios');
})->name('iosPost');

//Route::get('/', 'Auth\LoginController@showLoginForm')->name('home');

Route::get('/terms/client', function (Request $request) {
    return view('terms', ['for' => 'client']);
})->name('termsClient');
Route::get('/terms/dr', function (Request $request) {
    return view('terms', ['for' => 'dr']);
})->name('termsDr');

Auth::routes();

// Authentication routes with throttle
// Later we have to add recaptcha to this routes
// every 1 min 3000 requests
Route::middleware('throttle:2,1')->group(function () {
    Route::post('register', 'Auth\RegisterController@register');
    Route::post('login', 'Auth\LoginController@login');
});
Route::middleware('throttle:2,2')->group(function () {
    Route::post('forgotPass', 'Auth\ForgotPasswordController@recoverPassSms')->name('forgotPassSMS');
});

// Resources without auth
Route::get('register/client', 'Auth\RegisterController@showRegistrationFormClient')->name('registerClient');
Route::get('register/doctor', 'Auth\RegisterController@showRegistrationFormDoctor')->name('registerDoctor');
Route::get('/payir', 'PaymentController@pay')->name('pay');
Route::get('/payir/callback', 'PaymentController@verify');


// Routes need auth
Route::middleware(['auth', 'role'])->group(function () {
    Route::get('panel', 'PanelController@index')->name('panel');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::resource('reqs', 'UserRequestController');
    Route::get('profile', 'Auth\LoginController@current_user')->name('profile');
    Route::match(['put', 'patch'], 'user/update', 'Auth\RegisterController@update')->name('updateProfile');
    Route::resource('sicks', 'UserSickController');
    Route::resource('complaints', 'ComplaintController');
    Route::resource('chats', 'ChatController');
    Route::get('wallet/increase', 'WalletController@increaseIndex')->name('wallet.index');
    Route::get('wallet/income', 'WalletController@income')->name('wallet.income');
    Route::post('wallet/increase', 'WalletController@increase')->name('wallet.increase');

    //dr routes should set middleware later
    Route::post('reqs/new/{req}', 'UserRequestController@acceptRequestDr')->name('acceptReq');
    Route::post('reqs/close/{req}', 'UserRequestController@closeRequestDr')->name('closeReq');
    Route::post('reqs/reject/{req}', 'UserRequestController@rejectRequestDr')->name('rejectReq');

    Route::group(['prefix' => env('ADMIN_PREFIX/') . 'admin'], function () {
        Voyager::routes();
        Route::get('reqs/cost/back', 'UserRequestController@costBack')->name('costBack');
        Route::get('doctor/accept', 'DoctorController@accept')->name('drAccept');
    });

});

capsul laravel/app/Doctor.php
<?php

namespace App;


use Storage;

class Doctor extends MotherModel
{
    protected $primaryKey = 'user_id';

    public function User()
    {
        return $this->belongsTo(User::class);
    }

    public function Expertise()
    {
        return $this->belongsTo(Expertise::class, 'exp_id', 'id');
    }

    public function Requests()
    {
        return $this->hasMany(UserRequest::class);
    }

    public function Complaints()
    {
        return $this->hasMany(Complaint::class);
    }


    public function getDocumentsPathAttribute($value)
    {
        $request = request();
        if ($request->expectsJson() or isNotAdmin())
            return $value ? url(Storage::url($value)) : null;
        else
            return $value;

    }

    public function getNameAttribute($value)
    {
        if (isAdmin())
            return $value . "(" . $this->user_id . ")";
    }
}

capsul laravel/app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Doctor;
use App\User;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Doctor $doctor
     * @return \Illuminate\Http\Response
     */
    public function show(Doctor $doctor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Doctor $doctor
     * @return \Illuminate\Http\Response
     */
    public function edit(Doctor $doctor)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Doctor $doctor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Doctor $doctor)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Doctor $doctor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Doctor $doctor)
    {
        //
    }

    public function accept(Request $request)
    {
        if (isNotAdmin())
            throw new NotFoundHttpException();
        $request->validate([
            'dr_id' => 'required|exists:doctors,user_id'
        ]);
        $dr = User::find($request->dr_id);
        $dr->status = 'active';
        $dr->save();
        flashMsg('دکتر با موفقیت تایید شد');
        return redirect()->back();

    }
}

capsul laravel/resources/views/doctor/requests/create.blade.php
@extends('layouts.doctor.doctorPanel')

@section('content')
    {{--    @if($errors->any())--}}
    {{--        @foreach($errors->all() as $error)--}}
    {{--            <div class="text-center mx-auto my-4 five-second-fade">--}}
    {{--                <span class="alert alert-class alert-danger alert-dismissible--}}
    {{--                    text-center">--}}
    {{--                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"--}}
    {{--                            style="margin-left: 8px!important;">&times;--}}
    {{--                    </button>--}}
    {{--                    {{$error}}</span>--}}
    {{--            </div>--}}
    {{--        @endforeach--}}
    {{--    @endif--}}
    <div class="card card-primary mt-3 mx-auto" style="max-width: 600px">
        <div class="card-header">
            <h3 class="card-title">درخواست خدمت جدید</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{route('reqs.store')}}" method="post" id="thisForm">
            @csrf
            <input type="hidden" class="hidden-date" name="reserve_date" value="{{old('reserve_date')}}">
            <div class="card-body">
                <div class="form-group">
                    <label class="col-sm-10">در صورت رزرو تاریخ را انتخاب کنید</label>

                    <div class="input-group col-sm-10">
                        <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="fa fa-calendar"></i>
                      </span>
                        </div>
                        <input class="date-picker form-control" name="persian_date" value="{{old('persian_date')}}"
                               readonly/>

                    </div>
                    @error('reserve_date')
                    <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="col-sm-10 control-label" for="inputForType">نوع خدمت&nbsp;<i
                                class="fa fa-star text-danger"></i></label>
                    <div class="col-sm-10">
                        <select class="form-control" name="type" id="inputForType" required>
                            @if(old('type') == 'lab')
                                <option value="lab" selected>آزمایشگاهی</option>
                                <option value="renew_prescription">تمدید نسخه</option>
                                <option value="send_prescription">ارسال نسخه</option>
                            @elseif(old('type') == 'renew_prescription')
                                <option value="lab">آزمایشگاهی</option>
                                <option value="renew_prescription" selected>تمدید نسخه</option>
                                <option value="send_prescription">ارسال نسخه</option>
                            @elseif(old('type') == 'send_prescription')
                                <option value="lab">آزمایشگاهی</option>
                                <option value="renew_prescription">تمدید نسخه</option>
                                <option value="send_prescription" selected>ارسال نسخه</option>
                            @else
                                <option selected disabled>انتخاب کنید</option>
                                <option value="lab">آزمایشگاهی</option>
                                <option value="renew_prescription">تمدید نسخه</option>
                                <option value="send_prescription">ارسال نسخه</option>
                            @endif
                        </select>
                        @error('type')
                        <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-10 control-label" for="inputExp">نوع تخصص&nbsp;<i
                                class="fa fa-star text-danger"></i></label>
                    <div class="col-sm-10">

                        <select class="form-control @error('exp_id') is-invalid @enderror"
                                id="inputExp" name="exp_id" required>
                            <option selected disabled>انتخاب کنید</option>
                            @foreach(\App\Expertise::all() as $exp)
                                <option value="{{$exp->id}}" data-cost="{{$exp->cost}}"
                                        @if (old('exp_id') == $exp->id) selected @endif>{{$exp->expertise_name}}</option>
                            @endforeach
                        </select>
                        @error('exp_id')
                        <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>

                </div>
                <div class="form-group">
                    <label for="main_reason" class="col-sm-10 control-label">دلیل اصلی مراجعه امروز شما به پزشک&nbsp;<i
                                class="fa fa-star text-danger"></i></label>

                    <div class="col-sm-10">
                                    <textarea name="main_reason" rows=2 required
                                              class="form-control @error('main_reason') is-invalid @enderror"
                                              id="main_reason"
                                              placeholder="دلیل خود را بنویسید">{{ old('main_reason') }}</textarea>
                        @error('main_reason')
                        <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for="answer1" class="col-sm-10 control-label">از چه زمانی شروع ویا تشدید شده است؟</label>

                    <div class="col-sm-10">
                                    <textarea name="answer1" rows=2
                                              class="form-control @error('answer1') is-invalid @enderror" id="answer1"
                                              placeholder="زمان مورد نظر را دقیق وارد نمایید">{{old('answer1')}}</textarea>
                        @error('answer1')
                        <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for="answer2" class="col-sm-10 control-label">علائم همراه را نام ببرید:</label>

                    <div class="col-sm-10">
                                    <textarea name="answer2" rows=2
                                              class="form-control @error('answer2') is-invalid @enderror" id="answer2"
                                              placeholder="مثلا تب یا سرفه">{{old('answer2')}}</textarea>
                        @error('answer2')
                        <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for="answer3" class="col-sm-10 control-label">آیا دارویی نیز مصرف کرده‌اید؟</label>

                    <div class="col-sm-10">
                                    <textarea name="answer3" rows=2
                                              class="form-control @error('answer3') is-invalid @enderror" id="answer3"
                                              placeholder="چه دارویی، ‌چه مقدار و مدت زمان مصرف را بنویسید">{{old('answer3')}}</textarea>
                        @error('answer3')
                        <span class="invalid text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                </div>

                <div class="mx-3">
                    <h6 class="text-bold">مبلغ قابل پرداخت:</h6>
                    <h4 class="text-danger"><span class="text-danger" id="cost">0</span> تومان</h4>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <!--                                <button type="submit" class="btn btn-primary">اتخاب پزشک</button>-->
                <button type="submit" class="btn btn-success btn-lg">تایید و ادامه</button>
                <a class="btn btn-primary btn-lg" href="{{route('reqs.index')}}">بازگشت</a>
            </div>
        </form>
    </div>

@endsection

@section('script')
    <script>
        $('#inputExp').change(function () {
            var cost = $(this).find(':selected').data('cost')
            $('#cost').text(toPersianNum(cost));
        });
        $('.date-picker').persianDatepicker({
            initialValue: false,
            format: 'YYYY/MM/DD',
        });
        $('#thisForm').submit(function (e) {
            e.preventDefault();
            var date = $('.date-picker').val();
            if(date){
                date = toEnglishNum(date);
                date = date.split('/');
                date = date.map(Number);
                date = new persianDate(date).toCalendar('gregorian').toLocale('en').format('YYYY/MM/DD');
                $('.hidden-date').val(date)
            }
            $(this).unbind().submit();
        });
    </script>
@endsection

capsul laravel/resources/views/doctor/requests/index.blade.php
@extends('layouts.doctor.doctorPanel')

@section('content')
    <div class="card card-primary mt-3">
        <div class="card-header">
            <h3 class="card-title">لیست درخواست ها</h3>
        </div>
        <div class="card-body row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{$reqs->where('status','accepted')->count()}}</h3>

                        <p>درخواست های قبول شده</p>
                        <span class="badge badge-danger invisible" >  پیام جدید</span>

                    </div>
                    <div class="icon">
                        <i class="fa fa-plus"></i>
                    </div>
                    <a href="{{route('reqs.index').'?status[0]=accepted'}}" class="small-box-footer">مشاهده <i
                                class="fa fa-arrow-circle-left"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>{{$newReqs->where('status','waiting')->count()}}</h3>

                        <p>درخواست های منتظر پاسخ</p>
                        @php($newWaiting = newWaitingChecker($newReqs))
                        <span class="badge badge-danger @if(!$newWaiting) invisible @endif" >{{$newWaiting}} جدید</span>

                    </div>
                    <div class="icon">
                        <i class="fa fa-pause"></i>
                    </div>
                    <a href="{{route('reqs.index').'?status[0]=waiting'}}" class="@if($newWaiting) bg-warn-dang-flasher @endif small-box-footer">مشاهده
                        <i
                                class="fa fa-arrow-circle-left"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-gray">
                    <div class="inner">
                        <h3>{{$reqs->where('status','finished')->count()}}</h3>

                        <p>درخواست های پایان یافته</p>
                        <span class="badge badge-danger invisible" >O</span>

                    </div>
                    <div class="icon">
                        <i class="fa fa-check"></i>
                    </div>
                    <a href="{{route('reqs.index').'?status[0]=finished'}}" class="small-box-footer">مشاهده <i
                                class="fa fa-arrow-circle-left"></i></a>
                </div>
            </div>
        {{--            <div class="col-lg-3 col-6">--}}
        {{--                <!-- small box -->--}}
        {{--                <div class="small-box bg-info">--}}
        {{--                    <div class="inner">--}}
        {{--                        <h3>{{$reqs->where('status','reserved')->count()}}</h3>--}}

        {{--                        <p>درخواست های رزور شده</p>--}}
        {{--                    </div>--}}
        {{--                    <div class="icon">--}}
        {{--                        <i class="fa fa-clock-o"></i>--}}
        {{--                    </div>--}}
        {{--                    <a href="{{route('reqs.index').'?status[0]=reserved'}}" class="small-box-footer">مشاهده <i class="fa fa-arrow-circle-left"></i></a>--}}
        {{--                </div>--}}
        {{--            </div>--}}
        <!-- ./col -->
        </div>
        {{--        <div class="card-footer text-center">--}}
        {{--            <a href="{{route('reqs.create')}}" class="btn btn-lg btn-primary">درخواست خدمت جدید</a>--}}
        {{--        </div>--}}
    </div>


@endsection
@section('script')
    <script>
        setInterval(function () {
            if ($('.bg-warn-dang-flasher').hasClass('bg-danger'))
                $('.bg-warn-dang-flasher').removeClass('bg-danger').addClass('bg-gray-light');
            else if ($('.bg-warn-dang-flasher').hasClass('bg-gray-light'))
                $('.bg-warn-dang-flasher').removeClass('bg-gray-light').addClass('bg-danger');
            else
                $('.bg-warn-dang-flasher').addClass('bg-danger');
        }, 500);

    </script>
@endsection

capsul laravel/resources/views/doctor/requests/list.blade.php
@extends('layouts.doctor.doctorPanel')

@section('content')
    <div class="card card-primary mt-3">
        <div class="card-header">
            <h3 class="card-title">
                {{translateRequestTitle($type)}}
            </h3>
        </div>
        <div class="card-body row">
            @if($reqs->isEmpty())
                <div class="text-center w-100">
                    <h5 class="text-warning">در این بخش درخواستی وجود ندارد</h5>
                </div>
            @endif
            @foreach($reqs as $req)
                <div class="card col-lg-4">
                    <div class="card-body">
                        <span class="my-1 ill-name">{{translateRequestType($req)}}</span>
                        @php
                                $dateTime = new \Hekmatinasser\Verta\Verta($req->created_at);
                                $date = $dateTime->format('Y/n/j');
                        @endphp
                        <span class="my-1 float-left small mt-1">{{$date}}</span><br>
                        @if($req->status == 'accepted')
                            <span class="my-1 badge badge-success">{{translateRequestStatus($req)}}</span>
                        @elseif($req->status == 'waiting')
                            <span class="my-1 badge badge-warning">{{translateRequestStatus($req)}}</span>
                        @elseif($req->status == 'reserved')
                            <span class="my-1 badge badge-info">{{translateRequestStatus($req)}}</span>
                        @elseif($req->status == 'finished')
                            <span class="my-1 badge badge-dark">{{translateRequestStatus($req)}}</span>
                        @else
                            <span class="my-1 badge badge-danger">{{translateRequestStatus($req)}}</span>
                        @endif

                        <div class="d-flex my-3">
                            @if($req->Client and $req->Client->User->pic)
                                <div class="image">
                                    <img src="{{$req->Client->User->pic}}" class="img-circle elevation-2"
                                         alt="User Image"
                                         style="width: 3.5rem">
                                </div>
                            @elseif($req->Client)
                                <div class="image">
                                    <img src="{{asset('dist/img/avatar04.png')}}" class="img-circle elevation-2"
                                         alt="User Image"
                                         style="width: 3.5rem">
                                </div>
                            @endif

                            <div class="info mr-3">
                                @if($req->user_id)
                                    <a class="d-block">{{$req->Client->User->fname . ' '. $req->Client->User->lname}}</a>
                                    <a class="d-block">سن: {{$req->Client->age ?? 'تعیین نشده'}}</a>
                                @endif

                            </div>
                        </div>
                        <a href="{{route('reqs.show',['req'=>$req])}}"
                           class="my-1 btn btn-dark btn-sm">اطلاعات بیشتر</a>
                        <br>
                    </div>
                </div>

            @endforeach

        </div>
        <div class="card-footer text-center">
            <a href="{{route('reqs.index')}}" class="btn btn-lg btn-primary">بازگشت</a>
        </div>
    </div>

@endsection